### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/iphone-filter-demo#1]
Hey @cjgammon!
Long time no talk! 😄Maybe you don't remember me - my name is Fil, and I'm (recently) part of Adobe’s Open Source Office. I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project?

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project?

Thanks for any info.

-Fil

**Comment by dirkschulze** [comment]
@filmaj It is probably fine to archive this project.

**Comment by cjgammon** [comment]
@filmaj Hey Fil!
It's fine to archive this.  I don't see anything happening with this.

**Comment by filmaj** [comment]
OK. I have updated the README to reflect its status and will archive shortly.
